import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'config/routes/app_router.dart';
import 'config/theme/app_theme.dart';
import 'core/constants/storage_constants.dart';
import 'core/services/profile_sync_service.dart';
import 'features/auth/data/datasources/local/auth_local_datasource.dart';
import 'features/auth/data/models/user_model.dart';
import 'features/auth/presentation/bloc/auth_bloc.dart';
import 'features/auth/presentation/bloc/auth_event.dart';
import 'features/group/data/models/group_model.dart';
import 'features/trail/data/models/trail_model.dart';
import 'injection/injection.dart';

import 'features/settings/presentation/bloc/theme_bloc.dart';
import 'features/settings/presentation/bloc/theme_event.dart';
import 'features/settings/presentation/bloc/theme_state.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Set preferred orientations
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize Hive
  await _initHive();

  // Initialize dependencies
  await initializeDependencies();

  // Start profile sync service to sync pending updates when online
  sl<ProfileSyncService>().startListening();

  // Pre-check if user has an active session (fast local check)
  final isLoggedIn = await sl<AuthLocalDataSource>().isLoggedIn();

  // Run app
  runApp(GoTrekApp(isLoggedIn: isLoggedIn));
}


/// Initialize Hive database and register adapters
Future<void> _initHive() async {
  await Hive.initFlutter();

  // Register Hive Adapters
  // Note: These adapters will be generated by build_runner
  // Make sure to run: flutter pub run build_runner build
  _registerHiveAdapters();

  // Open required boxes
  await _openHiveBoxes();
}

/// Register all Hive type adapters
void _registerHiveAdapters() {
  // Auth Models
  if (!Hive.isAdapterRegistered(StorageConstants.userModelTypeId)) {
    Hive.registerAdapter(UserModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.emergencyContactModelTypeId)) {
    Hive.registerAdapter(EmergencyContactModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.userStatsModelTypeId)) {
    Hive.registerAdapter(UserStatsModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.completedTrailModelTypeId)) {
    Hive.registerAdapter(CompletedTrailModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.joinedTrailModelTypeId)) {
    Hive.registerAdapter(JoinedTrailModelAdapter());
  }

  // Trail Models
  if (!Hive.isAdapterRegistered(StorageConstants.trailModelTypeId)) {
    Hive.registerAdapter(TrailModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.durationModelTypeId)) {
    Hive.registerAdapter(DurationModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.ratingModelTypeId)) {
    Hive.registerAdapter(RatingModelAdapter());
  }

  // Group Models
  if (!Hive.isAdapterRegistered(StorageConstants.groupModelTypeId)) {
    Hive.registerAdapter(GroupModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.groupParticipantTypeId)) {
    Hive.registerAdapter(GroupParticipantModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.meetingPointTypeId)) {
    Hive.registerAdapter(MeetingPointModelAdapter());
  }
  if (!Hive.isAdapterRegistered(StorageConstants.groupCommentTypeId)) {
    Hive.registerAdapter(GroupCommentModelAdapter());
  }

  // Message Models - will be added when Chat feature is implemented
}

/// Open all required Hive boxes
Future<void> _openHiveBoxes() async {
  await Future.wait([
    Hive.openBox<dynamic>(StorageConstants.userBox),
    Hive.openBox<TrailModel>(StorageConstants.trailBox),
    Hive.openBox<GroupModel>(StorageConstants.groupBox),
    Hive.openBox<dynamic>(StorageConstants.settingsBox),
    Hive.openBox<dynamic>(StorageConstants.cacheBox),
    Hive.openBox<dynamic>(StorageConstants.syncBox),
  ]);
}

/// Main Application Widget
class GoTrekApp extends StatefulWidget {
  final bool isLoggedIn;

  const GoTrekApp({super.key, required this.isLoggedIn});

  @override
  State<GoTrekApp> createState() => _GoTrekAppState();
}

class _GoTrekAppState extends State<GoTrekApp> {
  late final AuthBloc _authBloc;
  late final dynamic _router;
  late final ThemeBloc _themeBloc;

  @override
  void initState() {
    super.initState();
    _authBloc = sl<AuthBloc>();
    _router = AppRouter.createRouter(_authBloc, skipSplash: widget.isLoggedIn);

    _themeBloc = sl<ThemeBloc>();
    _themeBloc.add(const LoadThemePreferenceEvent());

    _authBloc.add(const CheckAuthStatusEvent());
  }

  @override
  void dispose() {
    // Don't close singleton blocs — they are managed by GetIt
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<AuthBloc>.value(value: _authBloc),
        BlocProvider<ThemeBloc>.value(value: _themeBloc),
      ],
      child: BlocBuilder<ThemeBloc, ThemeState>(
        builder: (context, themeState) {
          return MaterialApp.router(
            title: 'GOTrek',
            debugShowCheckedModeBanner: false,

            // Theme
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeState.themeMode,

            // Router
            routerConfig: _router,

            // Localization (can be added later)
            // localizationsDelegates: [...],
            // supportedLocales: [...],
          );
        },
      ),
    );
  }
}

