// Mocks generated by Mockito 5.4.4 from annotations
// in gotrek/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i11;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gotrek/core/errors/failures.dart' as _i7;
import 'package:gotrek/core/usecases/usecase.dart' as _i16;
import 'package:gotrek/features/auth/domain/entities/user_entity.dart' as _i8;
import 'package:gotrek/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:gotrek/features/auth/domain/usecases/change_password_usecase.dart'
    as _i19;
import 'package:gotrek/features/auth/domain/usecases/check_auth_status_usecase.dart'
    as _i18;
import 'package:gotrek/features/auth/domain/usecases/forgot_password_usecase.dart'
    as _i20;
import 'package:gotrek/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i17;
import 'package:gotrek/features/auth/domain/usecases/login_usecase.dart'
    as _i12;
import 'package:gotrek/features/auth/domain/usecases/logout_usecase.dart'
    as _i15;
import 'package:gotrek/features/auth/domain/usecases/register_usecase.dart'
    as _i14;
import 'package:gotrek/features/auth/domain/usecases/reset_password_usecase.dart'
    as _i21;
import 'package:gotrek/features/auth/domain/usecases/signup_usecase.dart'
    as _i13;
import 'package:gotrek/features/auth/domain/usecases/update_profile_usecase.dart'
    as _i23;
import 'package:gotrek/features/auth/domain/usecases/upload_profile_image_usecase.dart'
    as _i22;
import 'package:gotrek/features/group/domain/entities/group_entity.dart'
    as _i10;
import 'package:gotrek/features/group/domain/repositories/group_repository.dart'
    as _i5;
import 'package:gotrek/features/group/domain/usecases/create_group.dart'
    as _i30;
import 'package:gotrek/features/group/domain/usecases/get_group_by_id.dart'
    as _i32;
import 'package:gotrek/features/group/domain/usecases/get_groups.dart' as _i31;
import 'package:gotrek/features/group/domain/usecases/get_my_groups.dart'
    as _i33;
import 'package:gotrek/features/group/domain/usecases/get_pending_requests.dart'
    as _i36;
import 'package:gotrek/features/group/domain/usecases/leave_group.dart' as _i37;
import 'package:gotrek/features/group/domain/usecases/manage_join_request.dart'
    as _i35;
import 'package:gotrek/features/group/domain/usecases/request_join_group.dart'
    as _i34;
import 'package:gotrek/features/group/domain/usecases/update_group.dart'
    as _i38;
import 'package:gotrek/features/trail/domain/entities/trail_entity.dart' as _i9;
import 'package:gotrek/features/trail/domain/repositories/trail_repository.dart'
    as _i4;
import 'package:gotrek/features/trail/domain/usecases/complete_trail_usecase.dart'
    as _i29;
import 'package:gotrek/features/trail/domain/usecases/get_popular_trails_usecase.dart'
    as _i27;
import 'package:gotrek/features/trail/domain/usecases/get_trail_by_id_usecase.dart'
    as _i25;
import 'package:gotrek/features/trail/domain/usecases/get_trails_usecase.dart'
    as _i24;
import 'package:gotrek/features/trail/domain/usecases/join_trail_usecase.dart'
    as _i28;
import 'package:gotrek/features/trail/domain/usecases/search_trails_usecase.dart'
    as _i26;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRepository_1 extends _i1.SmartFake
    implements _i3.AuthRepository {
  _FakeAuthRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrailRepository_2 extends _i1.SmartFake
    implements _i4.TrailRepository {
  _FakeTrailRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupRepository_3 extends _i1.SmartFake
    implements _i5.GroupRepository {
  _FakeGroupRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> register({
    required String? name,
    required String? email,
    required String? password,
    required String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
              #phone: phone,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
              #phone: phone,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> signUp({
    required String? username,
    required String? email,
    required String? password,
    String? fullName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #username: username,
            #email: email,
            #password: password,
            #fullName: fullName,
            #phone: phone,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #username: username,
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #username: username,
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, bool>> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
            _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #isLoggedIn,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
                _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #isLoggedIn,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> forgotPassword(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#email: email},
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> resetPassword({
    required String? email,
    required String? otp,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #email: email,
            #otp: otp,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #email: email,
              #otp: otp,
              #newPassword: newPassword,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #email: email,
              #otp: otp,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, String?>> getAccessToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, String?>>.value(
            _FakeEither_0<_i7.Failure, String?>(
          this,
          Invocation.method(
            #getAccessToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, String?>>.value(
                _FakeEither_0<_i7.Failure, String?>(
          this,
          Invocation.method(
            #getAccessToken,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, String?>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, bool>> isTokenValid() =>
      (super.noSuchMethod(
        Invocation.method(
          #isTokenValid,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
            _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #isTokenValid,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
                _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #isTokenValid,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> uploadProfileImage(
          {required String? filePath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfileImage,
          [],
          {#filePath: filePath},
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #uploadProfileImage,
            [],
            {#filePath: filePath},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #uploadProfileImage,
            [],
            {#filePath: filePath},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> updateProfile({
    String? name,
    String? phone,
    String? bio,
    String? ageGroup,
    String? hikerType,
    String? emergencyContactName,
    String? emergencyContactPhone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #phone: phone,
            #bio: bio,
            #ageGroup: ageGroup,
            #hikerType: hikerType,
            #emergencyContactName: emergencyContactName,
            #emergencyContactPhone: emergencyContactPhone,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #name: name,
              #phone: phone,
              #bio: bio,
              #ageGroup: ageGroup,
              #hikerType: hikerType,
              #emergencyContactName: emergencyContactName,
              #emergencyContactPhone: emergencyContactPhone,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #name: name,
              #phone: phone,
              #bio: bio,
              #ageGroup: ageGroup,
              #hikerType: hikerType,
              #emergencyContactName: emergencyContactName,
              #emergencyContactPhone: emergencyContactPhone,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [TrailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrailRepository extends _i1.Mock implements _i4.TrailRepository {
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> getTrails(
          {_i9.TrailFilterParams? filters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrails,
          [],
          {#filters: filters},
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getTrails,
            [],
            {#filters: filters},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getTrails,
            [],
            {#filters: filters},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>> getTrailById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailById,
          [id],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>>.value(
            _FakeEither_0<_i7.Failure, _i9.TrailEntity>(
          this,
          Invocation.method(
            #getTrailById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>>.value(
                _FakeEither_0<_i7.Failure, _i9.TrailEntity>(
          this,
          Invocation.method(
            #getTrailById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> searchTrails(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTrails,
          [query],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #searchTrails,
            [query],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #searchTrails,
            [query],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<
      _i2.Either<_i7.Failure, List<_i9.TrailEntity>>> getTrailsByDifficulty(
          _i9.TrailDifficulty? difficulty) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailsByDifficulty,
          [difficulty],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getTrailsByDifficulty,
            [difficulty],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getTrailsByDifficulty,
            [difficulty],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> getTrailsByRegion(
          String? region) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailsByRegion,
          [region],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getTrailsByRegion,
            [region],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getTrailsByRegion,
            [region],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> getPopularTrails(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTrails,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getPopularTrails,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getPopularTrails,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> getFeaturedTrails(
          {int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedTrails,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getFeaturedTrails,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getFeaturedTrails,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> joinTrailWithDate({
    required String? trailId,
    required DateTime? startDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinTrailWithDate,
          [],
          {
            #trailId: trailId,
            #startDate: startDate,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #joinTrailWithDate,
            [],
            {
              #trailId: trailId,
              #startDate: startDate,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #joinTrailWithDate,
            [],
            {
              #trailId: trailId,
              #startDate: startDate,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> completeTrail(
          String? joinedTrailId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTrail,
          [joinedTrailId],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #completeTrail,
            [joinedTrailId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #completeTrail,
            [joinedTrailId],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> cancelJoinedTrail(
          String? joinedTrailId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelJoinedTrail,
          [joinedTrailId],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #cancelJoinedTrail,
            [joinedTrailId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #cancelJoinedTrail,
            [joinedTrailId],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> rateTrail({
    required String? trailId,
    required int? rating,
    String? review,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rateTrail,
          [],
          {
            #trailId: trailId,
            #rating: rating,
            #review: review,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #rateTrail,
            [],
            {
              #trailId: trailId,
              #rating: rating,
              #review: review,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #rateTrail,
            [],
            {
              #trailId: trailId,
              #rating: rating,
              #review: review,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<
      _i2.Either<_i7.Failure,
          List<_i9.TrailEntity>>> getCachedTrails() => (super.noSuchMethod(
        Invocation.method(
          #getCachedTrails,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getCachedTrails,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #getCachedTrails,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> cacheTrails(
          List<_i9.TrailEntity>? trails) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTrails,
          [trails],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #cacheTrails,
            [trails],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #cacheTrails,
            [trails],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> clearCachedTrails() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCachedTrails,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #clearCachedTrails,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #clearCachedTrails,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i5.GroupRepository {
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>> getGroups(
          {_i10.GroupFilterParams? filters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroups,
          [],
          {#filters: filters},
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #getGroups,
            [],
            {#filters: filters},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #getGroups,
            [],
            {#filters: filters},
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>> getGroupById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupById,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #getGroupById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #getGroupById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>> getMyGroups() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyGroups,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #getMyGroups,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #getMyGroups,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>> createGroup({
    required String? name,
    String? description,
    required String? trailId,
    required DateTime? startDate,
    DateTime? endDate,
    required int? maxParticipants,
    _i10.MeetingPoint? meetingPoint,
    required String? leaderId,
    List<_i11.File>? photos = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [],
          {
            #name: name,
            #description: description,
            #trailId: trailId,
            #startDate: startDate,
            #endDate: endDate,
            #maxParticipants: maxParticipants,
            #meetingPoint: meetingPoint,
            #leaderId: leaderId,
            #photos: photos,
          },
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #createGroup,
            [],
            {
              #name: name,
              #description: description,
              #trailId: trailId,
              #startDate: startDate,
              #endDate: endDate,
              #maxParticipants: maxParticipants,
              #meetingPoint: meetingPoint,
              #leaderId: leaderId,
              #photos: photos,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #createGroup,
            [],
            {
              #name: name,
              #description: description,
              #trailId: trailId,
              #startDate: startDate,
              #endDate: endDate,
              #maxParticipants: maxParticipants,
              #meetingPoint: meetingPoint,
              #leaderId: leaderId,
              #photos: photos,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>> updateGroup({
    required String? groupId,
    String? name,
    String? description,
    DateTime? startDate,
    DateTime? endDate,
    int? maxParticipants,
    _i10.MeetingPoint? meetingPoint,
    _i10.GroupStatus? status,
    String? title,
    String? location,
    List<String>? existingPhotos,
    List<String>? newPhotoPaths,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroup,
          [],
          {
            #groupId: groupId,
            #name: name,
            #description: description,
            #startDate: startDate,
            #endDate: endDate,
            #maxParticipants: maxParticipants,
            #meetingPoint: meetingPoint,
            #status: status,
            #title: title,
            #location: location,
            #existingPhotos: existingPhotos,
            #newPhotoPaths: newPhotoPaths,
          },
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #updateGroup,
            [],
            {
              #groupId: groupId,
              #name: name,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
              #maxParticipants: maxParticipants,
              #meetingPoint: meetingPoint,
              #status: status,
              #title: title,
              #location: location,
              #existingPhotos: existingPhotos,
              #newPhotoPaths: newPhotoPaths,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #updateGroup,
            [],
            {
              #groupId: groupId,
              #name: name,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
              #maxParticipants: maxParticipants,
              #meetingPoint: meetingPoint,
              #status: status,
              #title: title,
              #location: location,
              #existingPhotos: existingPhotos,
              #newPhotoPaths: newPhotoPaths,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> requestJoinGroup({
    required String? groupId,
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestJoinGroup,
          [],
          {
            #groupId: groupId,
            #message: message,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #requestJoinGroup,
            [],
            {
              #groupId: groupId,
              #message: message,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #requestJoinGroup,
            [],
            {
              #groupId: groupId,
              #message: message,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> approveJoinRequest({
    required String? groupId,
    required String? requestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveJoinRequest,
          [],
          {
            #groupId: groupId,
            #requestId: requestId,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #approveJoinRequest,
            [],
            {
              #groupId: groupId,
              #requestId: requestId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #approveJoinRequest,
            [],
            {
              #groupId: groupId,
              #requestId: requestId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> denyJoinRequest({
    required String? groupId,
    required String? requestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #denyJoinRequest,
          [],
          {
            #groupId: groupId,
            #requestId: requestId,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #denyJoinRequest,
            [],
            {
              #groupId: groupId,
              #requestId: requestId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #denyJoinRequest,
            [],
            {
              #groupId: groupId,
              #requestId: requestId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> leaveGroup(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveGroup,
          [groupId],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #leaveGroup,
            [groupId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #leaveGroup,
            [groupId],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<
      _i2.Either<_i7.Failure,
          List<_i10.JoinRequest>>> getPendingRequests() => (super.noSuchMethod(
        Invocation.method(
          #getPendingRequests,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.JoinRequest>>(
          this,
          Invocation.method(
            #getPendingRequests,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.JoinRequest>>(
          this,
          Invocation.method(
            #getPendingRequests,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupComment>> addComment({
    required String? groupId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [],
          {
            #groupId: groupId,
            #content: content,
          },
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupComment>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupComment>(
          this,
          Invocation.method(
            #addComment,
            [],
            {
              #groupId: groupId,
              #content: content,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupComment>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupComment>(
          this,
          Invocation.method(
            #addComment,
            [],
            {
              #groupId: groupId,
              #content: content,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupComment>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> deleteComment({
    required String? groupId,
    required String? commentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [],
          {
            #groupId: groupId,
            #commentId: commentId,
          },
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #deleteComment,
            [],
            {
              #groupId: groupId,
              #commentId: commentId,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #deleteComment,
            [],
            {
              #groupId: groupId,
              #commentId: commentId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> deleteGroup(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGroup,
          [groupId],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #deleteGroup,
            [groupId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #deleteGroup,
            [groupId],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);

  @override
  _i6.Future<
      _i2.Either<_i7.Failure,
          List<_i10.GroupEntity>>> getCachedGroups() => (super.noSuchMethod(
        Invocation.method(
          #getCachedGroups,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #getCachedGroups,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #getCachedGroups,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #clearCache,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #clearCache,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i12.LoginUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> call(
          _i12.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i13.SignUpUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> call(
          _i13.SignUpParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i14.RegisterUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> call(
          _i14.RegisterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i15.LogoutUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(_i16.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i17.GetCurrentUserUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> call(
          _i16.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [CheckAuthStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthStatusUseCase extends _i1.Mock
    implements _i18.CheckAuthStatusUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, bool>> call(_i16.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
            _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, bool>>.value(
                _FakeEither_0<_i7.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, bool>>);
}

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i19.ChangePasswordUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i19.ChangePasswordParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [ForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordUseCase extends _i1.Mock
    implements _i20.ForgotPasswordUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i20.ForgotPasswordParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i21.ResetPasswordUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i21.ResetPasswordParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [UploadProfileImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfileImageUseCase extends _i1.Mock
    implements _i22.UploadProfileImageUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> call(
          _i22.UploadProfileImageParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i23.UpdateProfileUseCase {
  @override
  _i3.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>> call(
          _i23.UpdateProfileParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
            _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>.value(
                _FakeEither_0<_i7.Failure, _i8.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [GetTrailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrailsUseCase extends _i1.Mock implements _i24.GetTrailsUseCase {
  @override
  _i4.TrailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TrailRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> call(
          _i24.GetTrailsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);
}

/// A class which mocks [GetTrailByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrailByIdUseCase extends _i1.Mock
    implements _i25.GetTrailByIdUseCase {
  @override
  _i4.TrailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TrailRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>> call(
          _i25.GetTrailByIdParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>>.value(
            _FakeEither_0<_i7.Failure, _i9.TrailEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>>.value(
                _FakeEither_0<_i7.Failure, _i9.TrailEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i9.TrailEntity>>);
}

/// A class which mocks [SearchTrailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTrailsUseCase extends _i1.Mock
    implements _i26.SearchTrailsUseCase {
  @override
  _i4.TrailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TrailRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> call(
          _i26.SearchTrailsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);
}

/// A class which mocks [GetPopularTrailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTrailsUseCase extends _i1.Mock
    implements _i27.GetPopularTrailsUseCase {
  @override
  _i4.TrailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TrailRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>> call(
          _i27.GetPopularTrailsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i9.TrailEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i9.TrailEntity>>>);
}

/// A class which mocks [JoinTrailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockJoinTrailUseCase extends _i1.Mock implements _i28.JoinTrailUseCase {
  @override
  _i4.TrailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TrailRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i28.JoinTrailParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [CompleteTrailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteTrailUseCase extends _i1.Mock
    implements _i29.CompleteTrailUseCase {
  @override
  _i4.TrailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTrailRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TrailRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i29.CompleteTrailParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [CreateGroupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateGroupUseCase extends _i1.Mock
    implements _i30.CreateGroupUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>> call(
          _i30.CreateGroupParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>);
}

/// A class which mocks [GetGroupsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGroupsUseCase extends _i1.Mock implements _i31.GetGroupsUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>> call(
          _i10.GroupFilterParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>);
}

/// A class which mocks [GetGroupByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGroupByIdUseCase extends _i1.Mock
    implements _i32.GetGroupByIdUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>);
}

/// A class which mocks [GetMyGroupsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyGroupsUseCase extends _i1.Mock
    implements _i33.GetMyGroupsUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>> call(
          _i16.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.GroupEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.GroupEntity>>>);
}

/// A class which mocks [RequestJoinGroupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestJoinGroupUseCase extends _i1.Mock
    implements _i34.RequestJoinGroupUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i34.RequestJoinGroupParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [ManageJoinRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockManageJoinRequestUseCase extends _i1.Mock
    implements _i35.ManageJoinRequestUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(
          _i35.ManageJoinRequestParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [GetPendingRequestsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingRequestsUseCase extends _i1.Mock
    implements _i36.GetPendingRequestsUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>> call(
          _i16.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.JoinRequest>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>>.value(
                _FakeEither_0<_i7.Failure, List<_i10.JoinRequest>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i10.JoinRequest>>>);
}

/// A class which mocks [LeaveGroupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaveGroupUseCase extends _i1.Mock implements _i37.LeaveGroupUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, void>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, void>>.value(
            _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, void>>.value(
                _FakeEither_0<_i7.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, void>>);
}

/// A class which mocks [UpdateGroupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateGroupUseCase extends _i1.Mock
    implements _i38.UpdateGroupUseCase {
  @override
  _i5.GroupRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGroupRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.GroupRepository);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>> call(
          _i38.UpdateGroupParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>.value(
                _FakeEither_0<_i7.Failure, _i10.GroupEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i10.GroupEntity>>);
}
